import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyleProvider from "../src/shared/styleProvider";
import Header from "../src/widgets/Header/ui";
import { ColorSchemeScript } from "@mantine/core";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <StyleProvider>
          <Header />
          <div className="sperator mt-[60px]" />
          {children}
        </StyleProvider>
      </body>
    </html>
  );
}
